version: '3'

volumes:
  influxdb:
  grafana:

services:

  influxdb:
      image: influxdb:1.8
      restart: unless-stopped
      ports:
        - "8083:8083"
        - "8086:8086"
        - "25826:25826/udp"
      volumes:
        - influxdb:/var/lib/influxdb

  grafana:
      image: grafana/grafana-oss
      user: "0:0"
      restart: unless-stopped
      ports:
        - "3000:3000"
      volumes:
        - grafana:/var/lib/grafana

  loxone2influx2:
    image: dusanmsk/loxone2influx2
    restart: unless-stopped
    ports:
      - "2222:2222/udp"
    environment:
      - TZ=Europe/Prague
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - INFLUXDB_DATABASE=loxone
      - BIND_ADDRESS=0.0.0.0
      - BIND_PORT=2222
