version: '3.3'

services:

  grafana:
    image: grafana/grafana:11.3.0
    restart: unless-stopped
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      - ${STORAGE_ROOT_PATH}/grafana:/var/lib/grafana

