version: '3'

volumes:
    influxdb_volume:
    grafana_volume:
    timescaledb_volume:

services:

  mosquitto:
    build: mosquitto
    restart: unless-stopped
    ports:
       - "1883:1883"
       - "9001:9001"

  node-lox-mqtt-gw:
    build: node-lox-mqtt-gateway
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      #- /data/docker_volumes/loxone_monitoring/influxdb:/var/lib/influxdb
      - influxdb_volume:/var/lib/influxdb

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      #- /data/docker_volumes/loxone_monitoring/timescaledb:/var/lib/postgresql/data        
      - timescaledb_volume:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:11.3.0
    restart: unless-stopped
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      #- /data/docker_volumes/loxone_monitoring/grafana:/var/lib/grafana
      - grafana_volume:/var/lib/grafana

  loxone2influx:
    build: loxone2influx
    restart: unless-stopped
    env_file:
      - .env

  loxone2timescale:
    build: loxone2timescale
    restart: unless-stopped
    env_file:
      - .env

