version: '3.3'

volumes:
  pgadmin-data:

services:

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ${STORAGE_ROOT_PATH}/timescaledb:/var/lib/postgresql/data

  loxone2timescale:
    build: timescaledb/loxone2timescale
    restart: unless-stopped
    env_file:
      - .env

